name: "Add package to repository"

on:
  repository_dispatch:
    types: [add-package]
  workflow_dispatch:
    inputs:
      url:
        description: "URL of the package to add"
        required: true
      dist:
        description: "Distribution to add the package to"
        required: true
      component:
        description: "Component to add the package to"
        required: true

jobs:
  add-package:
    name: "Add package"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: checkout
      
      - name: Fetch package
        id: fetch
        run: |
          if [[ "${{ github.event_name }}" = "repository_dispatch" && "${{ github.event.action }}" = "add-package" ]]; then
            URL="${{ github.event.client_payload.url }}"
            DIST="${{ github.event.client_payload.dist }}"
            COMPONENT="${{ github.event.client_payload.component }}"
          else
            URL="${{ github.event.inputs.url }}"
            DIST="${{ github.event.inputs.dist }}"
            COMPONENT="${{ github.event.inputs.component }}"
          fi

          echo "URL: $URL"
          echo "DIST: $DIST"
          echo "COMPONENT: $COMPONENT"

          # download package
          curl -LOJ $URL

          # figure out file and package name
          deb=$(ls *.deb | head -n 1)
          name=$(echo $deb | cut -d_ -f1)

          # copy package to repo
          target=checkout/pool/$DIST/$COMPONENT/$name
          mkdir -p $target && mv $deb $target

          echo "DEB=$deb" >> $GITHUB_ENV
          echo "DIST=$DIST" >> $GITHUB_ENV
          echo "COMPONENT=$COMPONENT" >> $GITHUB_ENV

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: checkout
          commit-message: "Add package ${{ env.DEB }} for ${{ env.DIST }}/${{ env.COMPONENT }}"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          title: "Add package ${{ env.DEB }} for ${{ env.DIST }}/${{ env.COMPONENT }}"
          body: |
            This PR adds the package ${{ env.DEB }} for ${{ env.DIST }}/${{ env.COMPONENT }} to the apt repository.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          delete-branch: true
          branch-suffix: short-commit-hash

