name: "Build pages"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure GPG key
        run: |
          echo -n "$GPG_SIGNING_KEY" | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      
      - name: Install apt-utils
        run: |
          apt -y install apt-utils

      - name: Cache apt-ftparchive db
        uses: actions/cache@v3
        with:
          path: cache
          key: ${[ runner.os }}-apt-ftparchive

      - name: Generate repository files
        run: |
          # prepare directory structure
          mkdir -p repo/dists/{bullseye}/{rpi}/{binary-armhf}
          mkdir -p cache

          # generate repo
          apt-ftparchive generate apt-ftparchive.conf
          
          # generate signed & unsigned Release files
          for dist in "bullseye"; do
            apt-ftparchive -c $dist.conf release repo/dists/$dist > repo/dists/$dist/Release
            gpg --default-key "apt@octoprint.org" -abs -o - repo/dists/$dist/Release > repo/dists/$dist/Release.gpg
            gpg --default-key "apt@octoprint.org" --clearsign -o - repo/dists/$dist/Release > repo/dists/$dist/InRelease
          done

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v2.0.0
        with:
          FOLDER: repo

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./repo
  
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
